---
title: Test RMarkdown
date: 5 Jan 2017
output:
  html_document:
    toc: true
    toc_depth: 3
    toc_float: true
    number_sections: true
    code_folding: hide
    theme: cosmo
---

```{r global_options, include = FALSE}
knitr::opts_chunk$set(	fig.width	= 10, 
						fig.height	= 7, 
						fig.path	= file.path(Sys.getenv("HOME"), "Desktop"),
						fig.align	= 'center', 
						dpi			= 300, 
						cache.path	= file.path(Sys.getenv("HOME"), "Desktop"),
						warning		= TRUE, 
						message		= TRUE,
						tidy		= TRUE)
```

# Main Header 1 {.tabset .tabset-fade}
## Second header - tabbed
Here is some text that will appear in HTML. I can make this _bold_ or __italic__
Below is a code chunk. Cache is FALSE here, but typically should be TRUE

```{r nameOfMyChunk, warning = TRUE, message = FALSE, cache = FALSE}
x <- rnorm(100)
plot(density(x))
```

We can also quote values outside of chunks that have already been defined.
_For example_ the length of object x plotted is: `r length(x)`

## Third header - tabbed

```{r functions, warning = TRUE, message = FALSE}
print("loading a library here: message from in-side of chunk")
library(ggsignif)
```

<!-- 
# Run the three lines below in console #
library(knitr)
library(rmarkdown)
render(input = "/path/to/sample_Markdown.rmd", output_file = "/out/path/sample_Markdown.html")
-->